FROM nimbix/ubuntu-desktop

ENV GIT_BRANCH testing
ENV TESTENV teststring
#RUN apt-get -y update && \
#    apt-get -y install curl && \
#    curl -H 'Cache-Control: no-cache' \
#        https://raw.githubusercontent.com/nimbix/image-common/$GIT_BRANCH/install-nimbix.sh \
#        | bash -s -- --setup-nimbix-desktop

RUN touch /etc/skel/.config/test

#EXPOSE 22
#ADD AppDef.json /etc/NAE/AppDef.json

